// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddWalletModalController from "./add_wallet_modal_controller"
application.register("add-wallet-modal", AddWalletModalController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import SignInController from "./sign_in_controller"
application.register("sign-in", SignInController)

import WalletsController from "./wallets_controller"
application.register("wallets", WalletsController)
