Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
