apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-rails
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
    - port: 3000
  selector:
    app: {{ .Values.appName }}
    tier: rails
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ .Values.appName }}-rails
spec:
  replicas: 1
  selector:
    app: {{ .Values.appName }}
    tier: rails
  template:
    metadata:
      name: {{ .Values.appName }}-rails
      labels:
        app: {{ .Values.appName }}
        tier: rails
    spec:
      containers:
      - name: {{ .Values.appName }}-rails
        image: {{ .Values.app.image }}
        args: {{ .Values.app.args }}
        env:
        {{- include "app.env" . | nindent 8 }}
        - name: RAILS_LOG_TO_STDOUT
          value: "true"
        - name: RAILS_SERVE_STATIC_ASSETS
          value: "true"
        ports:
        - containerPort: 3000
