apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-rails
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: 3000
  selector:
    app: {{ .Values.appName }}
    tier: rails
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.appName }}-rails
  lables: {{ .Values.appName }}
spec:
  replicas: 1
  minReadySeconds: 5
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
  selector:
    matchLables:
      app: {{ .Values.appName }}
      tier: rails
  template:
    metadata:
      name: {{ .Values.appName }}-rails
      labels:
        app: {{ .Values.appName }}
        tier: rails
    spec:
      containers:
      - name: {{ .Values.appName }}-rails
        image: {{ .Values.app.image }}
        command: {{ .Values.app.command }}
        args: {{ .Values.app.args }}
        env:
        {{- include "app.env" . | nindent 8 }}
        - name: RAILS_LOG_TO_STDOUT
          value: "true"
        - name: RAILS_SERVE_STATIC_ASSETS
          value: "true"
        ports:
        - containerPort: 3000
