{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.appName }}-migration
spec:
  ttlSecondsAfterFinished: 15
  template:
    metadata:
      name: {{ .Values.appName }}-migration
      labels:
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
      - name: {{ .Values.appName }}-setup
        image: {{ .Values.app.image }}
        args: {{ .Values.migration.args }}
        env:
        {{- include "app.env" . | nindent 8 }}
      restartPolicy: Never
{{- end }}