appName: bitpad

postgres:
  enabled: true
  image: postgres:9.6-alpine
  dbName: bitpad_prod
  storage:
    size:
      limited: true
      value: 4Gi
  secrets:
    user:
      name: db-user
      key: username
    password:
      name: db-user-pass
      key: password

redis: 
  enabled: true
  image: redis:3.2-alpine

migration:
  enabled: true
  args: ['rails db:create && rails db:migrate']
ingress:
  hostname: bitpad.ru

app:
  image: ghcr.io/emfy0/bitpad:latest
  args: ['rails s -p 3000 -b 0.0.0.0']
  secrets:
    secretKeyBase:
      name: secret-key-base
      key: secret-key-base
